system:
  version: "2.0.0-COMBAT"
  max_drones_mvp: 10                    # ❗ ТРЕБУЕТ ПЕРЕЗАПУСКА
  operator_location: "ukraine"

# LoRa связь - поддерживается GetLoRaFrequencies() и GetPowerConfig()
lora:
  primary_frequencies:                   # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
    - 433075000  # 433 MHz - дальний бой
    - 433175000
    - 433275000
    - 433375000

    # Европейские ISM (хорошее проникновение)
    - 868100000  # 868 MHz - основные
    - 868300000
    - 868500000
    - 868700000
    - 869000000
    - 869525000

    # Американские диапазоны
    - 915000000  # 915 MHz - высокая скорость
    - 915200000
    - 920000000
    - 922000000
    - 925000000

    # Дополнительные боевые частоты
    - 458000000  # UHF диапазон
    - 460000000
    - 2400000000 # 2.4 GHz - WiFi диапазон
    - 2450000000
  
  power_levels:                         # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
    min_power: 0                        # GetPowerConfig()
    max_power: 30                       # GetPowerConfig() 
    adaptive_step: 3                    # GetPowerConfig()
  
  mesh_config:                          # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
    enable_mesh: true                   # GetCommunicationConfig()
  
  frequency_hopping:                    # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
    enable: true                        # GetCommunicationConfig()
    hop_interval: 5000                  # GetCommunicationConfig()
    noise_threshold: -85.0              # GetCommunicationConfig()
    interference_threshold: -75.0       # GetCommunicationConfig()

# Video - поддерживается GetPowerConfig()
video:
  power_levels:                         # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
    min_power: 25                       # GetPowerConfig()
    max_power: 2500                     # GetPowerConfig()
    default_power: 200                  # GetPowerConfig()

# UWB позиционирование - поддерживается GetPowerConfig()
uwb:
  tx_power: 20                          # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ

# Безопасность - поддерживается GetCommunicationConfig()
security:
  enable_encryption: true               # ❗ ТРЕБУЕТ ПЕРЕЗАПУСКА
  shared_secret: "SlavaUkraini2024!"    # ❗ ТРЕБУЕТ ПЕРЕЗАПУСКА

# Аварийные процедуры - поддерживается PrintConfigurationSummary()
failsafe:
  enable_self_destruct: true            # ❗ ТРЕБУЕТ ПЕРЕЗАПУСКА

# Связь - поддерживается GetCommunicationConfig()
communication:                         # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
  timeout_ms: 5000                      # GetCommunicationConfig()
  heartbeat_interval_ms: 1000           # GetCommunicationConfig()
  max_retries: 5                        # GetCommunicationConfig()

# Формации - поддерживается GetFormationConfig()
formations:                             # ✅ ГОРЯЧЕЕ ОБНОВЛЕНИЕ
  wedge:                                # GetFormationConfig(FormationType::WEDGE)
    positions:
      - [0, 0, 0]      # Лидер
      - [-10, -10, 0]  # Левое крыло  
      - [10, -10, 0]   # Правое крыло
    spacing: 10.0
    tolerance: 3.0
  
  line:                                 # GetFormationConfig(FormationType::LINE)
    positions:
      - [0, 0, 0]
      - [15, 0, 0]
      - [30, 0, 0]
    spacing: 15.0
    tolerance: 3.0
  
  square:                               # GetFormationConfig(FormationType::SQUARE)
    positions:
      - [0, 0, 0]      # Center
      - [-10, -10, 0]  # Front left
      - [10, -10, 0]   # Front right
      - [-10, 10, 0]   # Rear left
      - [10, 10, 0]    # Rear right
    spacing: 10.0
    tolerance: 3.0